(.venv) vikimulhall@Viki community % heroku logs --tail
 ›   Error: The following error occurred:
 ›     Missing required flag app
 ›   See more help with --help
(.venv) vikimulhall@Viki community % heroku logs --tail --app community-noticeboard-app
2025-02-04T13:57:18.230158+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2025-02-04T13:57:18.230158+00:00 app[web.1]: File "/app/community_centre/wsgi.py", line 16, in <module>
2025-02-04T13:57:18.230158+00:00 app[web.1]: application = get_wsgi_application()
2025-02-04T13:57:18.230158+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-02-04T13:57:18.230158+00:00 app[web.1]: django.setup(set_prefix=False)
2025-02-04T13:57:18.230159+00:00 app[web.1]: ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-02-04T13:57:18.230159+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-02-04T13:57:18.230160+00:00 app[web.1]: apps.populate(settings.INSTALLED_APPS)
2025-02-04T13:57:18.230160+00:00 app[web.1]: ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-04T13:57:18.230161+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/apps/registry.py", line 116, in populate
2025-02-04T13:57:18.230162+00:00 app[web.1]: app_config.import_models()
2025-02-04T13:57:18.230162+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~~~~~~~~^^
2025-02-04T13:57:18.230162+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/apps/config.py", line 269, in import_models
2025-02-04T13:57:18.230162+00:00 app[web.1]: self.models_module = import_module(models_module_name)
2025-02-04T13:57:18.230162+00:00 app[web.1]: ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
2025-02-04T13:57:18.230162+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/importlib/__init__.py", line 88, in import_module
2025-02-04T13:57:18.230163+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2025-02-04T13:57:18.230171+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-04T13:57:18.230171+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2025-02-04T13:57:18.230179+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2025-02-04T13:57:18.230179+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
2025-02-04T13:57:18.230184+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
2025-02-04T13:57:18.230184+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
2025-02-04T13:57:18.230184+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2025-02-04T13:57:18.230184+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/contrib/auth/models.py", line 3, in <module>
2025-02-04T13:57:18.230185+00:00 app[web.1]: from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
2025-02-04T13:57:18.230185+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/contrib/auth/base_user.py", line 57, in <module>
2025-02-04T13:57:18.230185+00:00 app[web.1]: class AbstractBaseUser(models.Model):
2025-02-04T13:57:18.230185+00:00 app[web.1]: ...<109 lines>...
2025-02-04T13:57:18.230185+00:00 app[web.1]: )
2025-02-04T13:57:18.230185+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/db/models/base.py", line 143, in __new__
2025-02-04T13:57:18.230186+00:00 app[web.1]: new_class.add_to_class("_meta", Options(meta, app_label))
2025-02-04T13:57:18.230186+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-04T13:57:18.230186+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/db/models/base.py", line 371, in add_to_class
2025-02-04T13:57:18.230186+00:00 app[web.1]: value.contribute_to_class(cls, name)
2025-02-04T13:57:18.230186+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
2025-02-04T13:57:18.230186+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/db/models/options.py", line 243, in contribute_to_class
2025-02-04T13:57:18.230187+00:00 app[web.1]: self.db_table, connection.ops.max_name_length()
2025-02-04T13:57:18.230187+00:00 app[web.1]: ^^^^^^^^^^^^^^
2025-02-04T13:57:18.230187+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/utils/connection.py", line 15, in __getattr__
2025-02-04T13:57:18.230187+00:00 app[web.1]: return getattr(self._connections[self._alias], item)
2025-02-04T13:57:18.230187+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
2025-02-04T13:57:18.230187+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/utils/connection.py", line 62, in __getitem__
2025-02-04T13:57:18.230188+00:00 app[web.1]: conn = self.create_connection(alias)
2025-02-04T13:57:18.230188+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/db/utils.py", line 193, in create_connection
2025-02-04T13:57:18.230188+00:00 app[web.1]: backend = load_backend(db["ENGINE"])
2025-02-04T13:57:18.230188+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/db/utils.py", line 113, in load_backend
2025-02-04T13:57:18.230188+00:00 app[web.1]: return import_module("%s.base" % backend_name)
2025-02-04T13:57:18.230188+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/importlib/__init__.py", line 88, in import_module
2025-02-04T13:57:18.230188+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2025-02-04T13:57:18.230189+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-04T13:57:18.230189+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
2025-02-04T13:57:18.230189+00:00 app[web.1]: raise ImproperlyConfigured("Error loading psycopg2 or psycopg module")
2025-02-04T13:57:18.230189+00:00 app[web.1]: django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 or psycopg module
2025-02-04T13:57:18.230226+00:00 app[web.1]: [2025-02-04 13:57:18 +0000] [10] [INFO] Worker exiting (pid: 10)
2025-02-04T13:57:18.469459+00:00 app[web.1]: Traceback (most recent call last):
2025-02-04T13:57:18.470439+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/arbiter.py", line 209, in run
2025-02-04T13:57:18.470441+00:00 app[web.1]: self.sleep()
2025-02-04T13:57:18.470442+00:00 app[web.1]: ~~~~~~~~~~^^
2025-02-04T13:57:18.470468+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/arbiter.py", line 357, in sleep
2025-02-04T13:57:18.470469+00:00 app[web.1]: ready = select.select([self.PIPE[0]], [], [], 1.0)
2025-02-04T13:57:18.470474+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2025-02-04T13:57:18.470475+00:00 app[web.1]: self.reap_workers()
2025-02-04T13:57:18.470475+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~^^
2025-02-04T13:57:18.470475+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2025-02-04T13:57:18.470476+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2025-02-04T13:57:18.470479+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2025-02-04T13:57:18.470601+00:00 app[web.1]: 
2025-02-04T13:57:18.470602+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2025-02-04T13:57:18.470602+00:00 app[web.1]: 
2025-02-04T13:57:18.470604+00:00 app[web.1]: Traceback (most recent call last):
2025-02-04T13:57:18.471261+00:00 app[web.1]: File "/app/.heroku/python/bin/gunicorn", line 8, in <module>
2025-02-04T13:57:18.471263+00:00 app[web.1]: sys.exit(run())
2025-02-04T13:57:18.471264+00:00 app[web.1]: ~~~^^
2025-02-04T13:57:18.471264+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
2025-02-04T13:57:18.471265+00:00 app[web.1]: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2025-02-04T13:57:18.471265+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
2025-02-04T13:57:18.471267+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/app/base.py", line 231, in run
2025-02-04T13:57:18.471268+00:00 app[web.1]: super().run()
2025-02-04T13:57:18.471268+00:00 app[web.1]: ~~~~~~~~~~~^^
2025-02-04T13:57:18.471269+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/app/base.py", line 72, in run
2025-02-04T13:57:18.471270+00:00 app[web.1]: Arbiter(self).run()
2025-02-04T13:57:18.471270+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~^^
2025-02-04T13:57:18.471271+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/arbiter.py", line 229, in run
2025-02-04T13:57:18.471272+00:00 app[web.1]: self.halt(reason=inst.reason, exit_status=inst.exit_status)
2025-02-04T13:57:18.471273+00:00 app[web.1]: ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-04T13:57:18.471279+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/arbiter.py", line 342, in halt
2025-02-04T13:57:18.471280+00:00 app[web.1]: self.stop()
2025-02-04T13:57:18.471280+00:00 app[web.1]: ~~~~~~~~~^^
2025-02-04T13:57:18.471285+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/arbiter.py", line 393, in stop
2025-02-04T13:57:18.471285+00:00 app[web.1]: time.sleep(0.1)
2025-02-04T13:57:18.471285+00:00 app[web.1]: ~~~~~~~~~~^^^^^
2025-02-04T13:57:18.471290+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2025-02-04T13:57:18.471290+00:00 app[web.1]: self.reap_workers()
2025-02-04T13:57:18.471290+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~^^
2025-02-04T13:57:18.471300+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2025-02-04T13:57:18.471300+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2025-02-04T13:57:18.471317+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2025-02-04T13:57:18.580444+00:00 heroku[web.1]: Process exited with status 1
2025-02-04T13:57:18.604092+00:00 heroku[web.1]: State changed from starting to crashed

